import picture1 from '../images/picture-movie1.png';
import picture2 from '../images/picture-movie2.png';
import picture3 from '../images/picture-movie3.png';
import picture4 from '../images/picture-movie4.png';
import picture5 from '../images/picture-movie5.png';

const cardList = [
    {
        picture: picture1,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "1",
        isChecked: false,
        isShortMovie: false,
    },
    {
        picture: picture2,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "3",
        isChecked: true,
        isShortMovie: true,
    },
    {
        picture: picture3,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "4",
        isChecked: false, 
        isShortMovie: false,
    },
    {
        picture: picture4,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "5",
        isChecked: false,
        isShortMovie: false,
    },
    {
        picture: picture5,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "6",
        isChecked: false,
        isShortMovie: true,
    },
    {
        picture: picture1,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "7",
        isChecked: true,
        isShortMovie: false,
    },
    {
        picture: picture2,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "8",
        isChecked: true,
        isShortMovie: false,
    },
    {
        picture: picture3,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "9",
        isChecked: false,
        isShortMovie: true,
    },
    {
        picture: picture4,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "10",
        isChecked: false,
        isShortMovie: true,
    },
    {
        picture: picture5,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "11",
        isChecked: true,
        isShortMovie: false,
    },
    {
        picture: picture1,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "12",
        isChecked: false,
        isShortMovie: false,
    },
    {
        picture: picture2,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "13",
        isChecked: true,
        isShortMovie: false,
    },
    {
        picture: picture3,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "14",
        isChecked: false,
        isShortMovie: false,
    },
    {
        picture: picture4,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "15",
        isChecked: false,
        isShortMovie: true,
    },
    {
        picture: picture5,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "16",
        isChecked: false,
        isShortMovie: false,
    },
    {
        picture: picture1,
        title: "33 слова о дизайне",
        duration: "1ч42м",
        id: "17",
        isChecked: true,
        isShortMovie: false,
    },
];

export default cardList;